import type { NavbarState } from "../types";

export type ExportPayload = { fileName: string; mimeType: "text/plain;charset=utf-8"; content: string };

export function buildExportPayload(state: NavbarState, fileName = "navbar") : ExportPayload {
  return { fileName: `${fileName || "navbar"}.jsx`, mimeType: "text/plain;charset=utf-8", content: buildReactCode(state) };
}

export function buildReactCode(state: NavbarState) {
  return [
    "import * as React from \"react\";",
    "",
    "const state = " + JSON.stringify(state, null, 2) + ";",
  "",
  "function resolveFont(s) { return s.fontBucket === \"google\" ? '\"' + s.googleFontFamily + '\", sans-serif' : \"inherit\"; }",
  "function buildShadow(s) { if (!s.shadowEnabled) return \"none\"; var hex = Math.round(s.shadowOpacity * 255).toString(16).padStart(2, \"0\"); return s.shadowX + \"px \" + s.shadowY + \"px \" + s.shadowBlur + \"px \" + s.shadowSpread + \"px \" + s.shadowColor + hex; }",
    "",
    "export default function NavbarComponent() {",
    "  const navItems = Array.from({ length: state.navCount }, (_, index) => `Link ${index + 1}`);",
    "  const activeIndex = Math.max(0, Math.min(state.activeIndex, navItems.length - 1));",
    "  const isMobile = state.previewState === \"mobile\";",
    "  const isCollapsed = state.previewState === \"collapsed\" || (isMobile && state.mobileMode === \"collapse\");",
    "  const showDrawer = state.previewState === \"mobile\" && state.mobileMode === \"drawer\";",
    "  const [hoveredIndex, setHoveredIndex] = React.useState(null);",
    "  const [dropdownOpen, setDropdownOpen] = React.useState(false);",
    "  const style = {",
    "    width: state.width,",
    "    minHeight: isMobile ? state.height : \"auto\",",
    "    padding: state.padding,",
    "    margin: state.margin,",
    "    gap: state.gap,",
    "    borderRadius: state.radius,",
    "    border: `${state.borderWidth}px ${state.borderStyle} ${state.disabled && state.disabledUseCustomColors ? state.disabledBorder : state.border}`,",
    "        boxShadow: buildShadow(state),",
    "    background: state.background,",
    "    color: state.foreground,",
    "    fontFamily: resolveFont(state),",
    "    cursor: state.disabled ? state.disabledCursor : undefined,",
    "    position: state.sticky ? \"sticky\" : \"relative\",",
    "    top: state.sticky ? 0 : undefined,",
    "    transition: state.motion ? \"all 180ms ease\" : undefined,",
    "  };",
    "",
    "  return (",
    "    <nav id={state.id} aria-label={state.landmarkLabel} tabIndex={state.tabIndex} style={style}>",
    "      <div style={{ display: \"flex\", flexWrap: \"wrap\", alignItems: \"center\", justifyContent: \"space-between\", gap: state.gap }}>",
    "        <a href=\"#\" style={{ display: \"flex\", alignItems: \"center\", gap: Math.max(6, state.gap / 3), color: state.foreground, fontSize: state.titleSize, fontWeight: state.fontWeight, textDecoration: \"none\" }}>",
    "          <span aria-hidden=\"true\" style={{ width: state.logoSize, height: state.logoSize, borderRadius: state.logoRadius, background: state.accent, flexShrink: 0 }} />",
    "          {state.title}",
    "        </a>",
    "        <button type=\"button\" aria-expanded={showDrawer || !isCollapsed} style={{ border: `1px solid ${state.border}`, borderRadius: 999, padding: \"8px 12px\", color: state.foreground, background: showDrawer ? state.accent : \"transparent\" }}>Menu</button>",
    "        <div style={{ display: isMobile || !isCollapsed ? \"flex\" : \"none\", flexWrap: \"wrap\", width: isMobile ? \"100%\" : \"auto\", gap: state.gap, background: isMobile ? state.mobileMenuBg : undefined, border: isMobile ? `1px solid ${state.mobileMenuBorder}` : undefined, borderRadius: isMobile ? 12 : undefined, padding: isMobile ? state.padding : undefined }}>",
    "          {navItems.map((item, index) => {",
    "            const active = index === activeIndex || (state.previewState === \"active\" && index === 0);",
    "            const isHovered = hoveredIndex === index || (state.previewState === \"hover\" && index === 0);",
    "            const isDropdownTrigger = state.hasDropdowns && index === 1;",
    "            return (",
    "              <div key={item} style={{ position: \"relative\" }}>",
    "                <a href=\"#\" aria-current={active ? \"page\" : undefined} aria-expanded={isDropdownTrigger ? dropdownOpen : undefined} style={{ position: \"relative\", borderRadius: 999, padding: \"8px 12px\", color: active ? state.activeItemText : isHovered ? state.hoverItemText : state.muted, background: active ? state.activeItemBg : isHovered ? state.hoverItemBg : \"transparent\", border: `1px solid ${active ? state.activeItemBorder : isHovered ? state.hoverItemBorder : \"transparent\"}`, outline: state.previewState === \"focus\" && index === activeIndex ? `2px solid ${state.accent}` : undefined, outlineOffset: 3, textDecoration: \"none\" }} onMouseEnter={() => { setHoveredIndex(index); if (isDropdownTrigger) setDropdownOpen(true); }} onMouseLeave={() => { setHoveredIndex(null); if (isDropdownTrigger) setDropdownOpen(false); }}>",
    "                  {item}{isDropdownTrigger ? \" +\" : \"\"}",
    "                  {active && <span aria-hidden=\"true\" style={{ position: \"absolute\", left: 12, right: 12, bottom: -1, height: state.indicatorHeight, background: state.indicatorColor, borderRadius: 999 }} />}",
    "                </a>",
    "                {isDropdownTrigger && dropdownOpen && (",
    "                  <div role=\"menu\" style={{ position: \"absolute\", top: \"100%\", left: 0, marginTop: 4, minWidth: 160, background: state.dropdownBg, border: `1px solid ${state.dropdownBorder}`, borderRadius: 10, boxShadow: state.dropdownShadow, padding: 6, zIndex: 20 }}>",
    "                    {[\"Sub item 1\", \"Sub item 2\", \"Sub item 3\"].map((sub) => (",
    "                      <a key={sub} href=\"#\" role=\"menuitem\" style={{ display: \"block\", borderRadius: 8, padding: \"8px 12px\", fontSize: 14, color: state.foreground, textDecoration: \"none\" }}>{sub}</a>",
    "                    ))}",
    "                  </div>",
    "                )}",
    "              </div>",
    "            );",
    "          })}",
    "        </div>",
    "        <div style={{ display: \"flex\", alignItems: \"center\", gap: Math.max(8, state.gap / 2) }}>",
    "          <a href=\"#\" style={{ color: state.muted, textDecoration: \"none\" }}>Log in</a>",
    "          <a href=\"#\" style={{ borderRadius: 999, padding: \"8px 16px\", background: state.accent, color: state.background, fontWeight: 700, textDecoration: \"none\" }}>Start</a>",
    "        </div>",
    "      </div>",
    "    </nav>",
    "  );",
    "}",
    "",
  ].join("\n");
}
